create:
  handler: handler.create
  events:
  - http:
      path: contents
      method: post
      authorizer: auth-check
      cors: true

update:
  handler: handler.update
  events:
  - http:
      path: contents/{id}
      method: put
      authorizer: auth-check
      cors: true

get:
  handler: handler.get
  events:
  - http:
      path: contents/{id}
      method: get
      cors: true

list:
  handler: handler.list
  events:
  - http:
      path: contents
      method: get
      cors: true
