service: onionful-api

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1

plugins:
  - serverless-offline
  - serverless-webpack

functions:
  hello:
    handler: index.handler
    events:
      - http:
          path: handler
          method: get
          cors: true
#      - http: ANY /
#      - http: 'ANY {proxy+}'
