list:
  events:
    - http:
        path: /
        method: get
        authorizer: auth-check
        cors: true

find:
  events:
  - http:
      path: /find/{query}
      method: get
      authorizer: auth-check
      cors: true
