list:
  events:
    - http:
        path: /{collection}
        method: get
        cors: true

create:
  events:
    - http:
        path: /{collection}
        method: post
        authorizer: auth-check
        cors: true

update:
  events:
    - http:
        path: /{collection}/{id}
        method: put
        authorizer: auth-check
        cors: true

get:
  events:
    - http:
        path: /{collection}/{id}
        method: get
        cors: true
