check:
  handler: handler.check
  cors: true

rotateToken:
  handler: handler.rotateToken
  cors: true
  events:
  - schedule: rate(8 hours)
  # TODO remove on production
  - http:
      path: rotate
      method: get
      cors: true
