create:
  events:
    - http:
        path: /
        method: post
        authorizer: auth-check
        cors: true

delete:
  events:
    - http:
        path: /{id}
        method: delete
        authorizer: auth-check
        cors: true

update:
  events:
    - http:
        path: /{id}
        method: put
        authorizer: auth-check
        cors: true

get:
  events:
    - http:
        path: /{id}
        method: get
        authorizer: auth-check
        cors: true

list:
  events:
    - http:
        path: /
        method: get
        authorizer: auth-check
        cors: true
